ekf_filter_node:
  ros__parameters:
    frequency: 50.0  # Hz
    sensor_timeout: 0.1  # seconds
    two_d_mode: true  # For a 2D robot, set to true
    odom0: "odom/wheel"  # Wheel odometry topic
    imu0: "sensors/imu/raw"    # IMU topic

    odom0_config: [false, false, false,  # x, y, z
                   false, false, false,  # roll, pitch, yaw
                   true, false, false,  # Vx, Vy, Vz
                   false, false, false]  # Vroll, Vpitch, Vyaw

    imu0_config: [false, false, false,  # x, y, z
                  false, false, true,   # roll, pitch, yaw
                  false, false, false,  # Vx, Vy, Vz
                  false, false, false]  # Vroll, Vpitch, Vyaw

    imu0_differential: false
    imu0_queue_size: 10
    odom0_queue_size: 10
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
