/**:
  ros__parameters:
    waypoints_path: "/home/mnmahir/ros_project/f1tenth/ws_robot/src/ugv_race/racelines/map_hijau.csv"
    
    base_frame: "base_footprint"
    map_frame: "map"
    read_frame_pose: true    # If false will get pose of base relative to map from odom_topic instead of tf
    read_frame_pose_rate: 50
    reverse_waypoints_order: true
    odom_topic: "/odom/map"
    drive_topic: "/cmd_auto/drive"
    rviz_current_waypoint_topic: "/current_waypoint"
    rviz_lookahead_waypoint_topic: "/lookahead_waypoint"

    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead);
    min_lookahead: 0.2
    max_lookahead: 1.0 # lookahead when the car is going around max velocity
    lookahead_ratio: 1.0 # approximately the max velocity
    K_p: 0.5
    steering_limit: 25.0
    velocity_percentage: 0.6 # the limit, can only do 1 lap with clean tires

    # Path Visualization Parameters
    rviz_waypoints_line_topic: "/waypoints_line"
    rviz_waypoints_arrow_topic: "/waypoints_arrow"
    waypoint_line_width: 0.281
    waypoint_arrow_length: 0.15
    waypoint_arrow_width: 0.05
    waypoint_arrow_height: 0.05
    waypoint_arrow_color: [0.0, 0.0, 0.0, 0.7] # rgba
