/**:
  ros__parameters:
    waypoints_path: "/home/mnmahir/ros_project/f1tenth/ws_robot/src/ugv_race/racelines/map_hijau.csv"
    
    base_frame: "base_footprint"
    map_frame: "map"
    read_frame_pose: true    # If false will get pose of base relative to map from odom_topic instead of tf
    read_frame_pose_rate: 50
    reverse_waypoints_order: true
    odom_topic: "/odom/map"
    drive_topic: "/cmd_auto/drive"
    rviz_current_waypoint_topic: "/current_waypoint"
    rviz_lookahead_waypoint_topic: "/lookahead_waypoint"

    # Follow Gap Parameters
    lidar_topic: "/scan"
    safety_radius: 0.5
    max_range: 3.0
    drive_speed: 1.0

    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead);
    min_lookahead: 0.2
    max_lookahead: 1.5 # lookahead when the car is going around max velocity
    lookahead_ratio: 1.0 # approximately the max velocity
    K_p: 0.7
    steering_limit: 22.9
    velocity_percentage: 0.7 # the limit, can only do 1 lap with clean tires


    # Avoidance Controller Parameters
    drive_topic_sub: "/ackermann_cmd"
    drive_topic_pub: "/ackermann_cmd_filtered"
    max_steering_angle: 22.9
    side_wall_width: 0.35
    side_wall_length: 0.424
    side_wall_length_offset: -0.324
    front_triangle_wall_width: 0.35
    front_triangle_wall_length: 0.2324       # 0.6024 - 0.27 (lidar distance from wheelbase) - offset
    front_triangle_wall_distance_offset: 0.1

    side_wall_avoidance_boundary_topic: "/side_wall_avoidance_boundary"



    # Path Visualization Parameters
    rviz_waypoints_line_topic: "/waypoints_line"
    rviz_waypoints_arrow_topic: "/waypoints_arrow"
    waypoint_line_width: 0.281
    waypoint_arrow_length: 0.15
    waypoint_arrow_width: 0.05
    waypoint_arrow_height: 0.05
    waypoint_arrow_color: [0.0, 0.0, 0.0, 0.7] # rgba
