/**:
  ros__parameters:
    waypoints_path: "racelines/f1tenth_route_long.csv"   # relative to the ugv_race share directory
    
    base_frame: "base_footprint"
    map_frame: "map"
    read_frame_pose: true    # If false will get pose of base relative to map from odom_topic instead of tf
    read_frame_pose_rate: 50
    reverse_waypoints_order: true
    odom_topic: "/odom/map"
    drive_topic: "/cmd_auto/drive"
    rviz_current_waypoint_topic: "/current_waypoint"
    rviz_lookahead_waypoint_topic: "/lookahead_waypoint"

    # Avoidance Controller Parameters
    scan_topic: "/scan"
    drive_topic_sub: "/ackermann_cmd"
    drive_topic_pub: "/ackermann_cmd_filtered"
    max_steering_angle: 22.9
    bubble_radius: 0.14505
    scan_rejection_distance: 5.0
    lidar_ray_fov: 119.0
    side_wall_width: 0.4
    side_wall_length: 0.474
    side_wall_length_offset: -0.324
    front_rectangle_wall_width: 0.4
    front_rectangle_wall_length: 1.25       # 0.6024 - 0.27 (lidar distance from wheelbase) - offset
    front_rectangle_wall_distance_offset: 0.15


    side_wall_avoidance_boundary_topic: "/side_wall_avoidance_boundary"


    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead);
    min_lookahead: 0.2
    max_lookahead: 1.25 # lookahead when the car is going around max velocity
    lookahead_ratio: 1.0 # approximately the max velocity
    K_p: 0.5
    steering_limit: 22.9
    velocity_percentage: 0.5 # the limit, can only do 1 lap with clean tires





    # Path Visualization Parameters
    rviz_waypoints_line_topic: "/waypoints_line"
    rviz_waypoints_arrow_topic: "/waypoints_arrow"
    waypoint_line_width: 0.281
    waypoint_arrow_length: 0.15
    waypoint_arrow_width: 0.05
    waypoint_arrow_height: 0.05
    waypoint_arrow_color: [0.0, 0.0, 0.0, 0.7] # rgba
